"""Multi-area RNN configuration.

A multi-area RNN is a single CTRNN whose hidden units are partitioned into
ordered areas (Area 0 -> Area 1 -> ...). Intra-area connectivity is dense;
inter-area connectivity is sparse, excitatory-only at the source, and split
into feedforward (downstream) and feedback (upstream) blocks. This matches the
architecture of Kleinman et al. 2025 (3 x 100 units, 10% ff E->E, 2-5% ff E->I,
5% fb E->E, Dale 80/20 per area).
"""
from __future__ import annotations

from ..constrained_rnn.configuration_constrained_rnn import ConstrainedRNNConfig


class MultiAreaRNNConfig(ConstrainedRNNConfig):
    """Config for a cascaded multi-area CTRNN.

    Args:
        area_sizes: Number of hidden units per area, e.g. (100, 100, 100).
            latent_dim is set to sum(area_sizes) and must not be passed separately.
        ei_ratio: Fraction of excitatory units *within each area* (default 0.8).
            Within an area the first round(n * ei_ratio) units are E, the rest I.
        intra_density: Density of the intra-area recurrent mask (default 1.0).
        ff_ee_density: Density of feedforward E->E connections between adjacent
            areas (default 0.10, Kleinman et al. 2025).
        ff_ei_density: Density of feedforward E->I connections (default 0.02;
            the paper scans 0-5%).
        fb_density: Density of feedback E->E connections between adjacent areas
            (default 0.05). Set to 0 for a purely feedforward cascade.
        fb_ei_density: Density of feedback E->I connections (default 0.0).
        input_areas: Indices of areas that receive the external input
            (default (0,): only the first area).
        input_e_only: If True, external input targets only E units of the input
            areas (default False: all units).
        output_area: Index of the area the readout reads from; negative indices
            count from the end (default -1: last area).
        output_e_only: If True (default), the readout reads only E units of the
            output area (Song et al. 2016 convention: long-range projections
            are excitatory).
        allow_self_connections: If False, removes autapses from the recurrent
            mask (default True, standard CTRNN).
        rec_spectral_radius: Target spectral radius of the *effective* recurrent
            matrix |W_rec * rec_mask| @ dale_signs at initialization (default
            1.0). The framework-default init explodes under Dale (|W| has a
            large positive mean), so the recurrent weights are rescaled by
            power-iteration at build time. Set to None to disable rescaling.
        spectral_norm_iters: Power-iteration steps for the spectral-radius
            estimate (default 100).
        mask_seed: RNG seed for sampling the sparse inter-area masks.
        All ConstrainedRNNConfig / CTRNNConfig arguments are inherited
        (dt, tau, activation, sigma_rec, nonlinearity_mode, freeze_*, ...).

    The masks themselves (rec_mask/in_mask/out_mask) and the per-area Dale sign
    vector (dale_signs) are generated by MultiAreaRNNModel from these
    hyperparameters and injected into the base ConstrainedRNNConfig, following
    the same pattern as sparse_rnn / modular_rnn; they are therefore
    reconstructed deterministically from mask_seed on load.
    """

    model_type = "multiarea_rnn"

    def __init__(
        self,
        area_sizes: tuple | list = (100, 100, 100),
        ei_ratio: float = 0.8,
        intra_density: float = 1.0,
        ff_ee_density: float = 0.10,
        ff_ei_density: float = 0.02,
        fb_density: float = 0.05,
        fb_ei_density: float = 0.0,
        input_areas: tuple | list = (0,),
        input_e_only: bool = False,
        output_area: int = -1,
        output_e_only: bool = True,
        allow_self_connections: bool = True,
        rec_spectral_radius: float | None = 1.0,
        spectral_norm_iters: int = 100,
        mask_seed: int = 42,
        **kwargs,
    ) -> None:
        area_sizes = [int(s) for s in area_sizes]
        if any(s <= 0 for s in area_sizes):
            raise ValueError(f"area_sizes must be positive, got {area_sizes}")
        latent_dim = int(sum(area_sizes))
        if "latent_dim" in kwargs and int(kwargs["latent_dim"]) != latent_dim:
            raise ValueError(
                f"latent_dim ({kwargs['latent_dim']}) != sum(area_sizes) ({latent_dim}); "
                "pass only area_sizes."
            )
        kwargs["latent_dim"] = latent_dim
        kwargs.setdefault("dale", True)
        n_areas = len(area_sizes)
        input_areas = tuple(int(a) for a in input_areas)
        for a in input_areas:
            if not (0 <= a < n_areas):
                raise ValueError(f"input_areas index {a} out of range for {n_areas} areas")
        output_area_resolved = int(output_area) % n_areas
        super().__init__(ei_ratio=ei_ratio, **kwargs)
        self.area_sizes = area_sizes
        self.intra_density = float(intra_density)
        self.ff_ee_density = float(ff_ee_density)
        self.ff_ei_density = float(ff_ei_density)
        self.fb_density = float(fb_density)
        self.fb_ei_density = float(fb_ei_density)
        self.input_areas = list(input_areas)
        self.input_e_only = bool(input_e_only)
        self.output_area = output_area_resolved
        self.output_e_only = bool(output_e_only)
        self.allow_self_connections = bool(allow_self_connections)
        self.rec_spectral_radius = rec_spectral_radius
        self.spectral_norm_iters = int(spectral_norm_iters)
        self.mask_seed = mask_seed
