"""Training layer: generic Trainer + paradigm-specific Objectives + nested cross-validation."""
from .trainer import Trainer
from .training_args import TrainingArguments
from .objectives import (
    Objective,
    OBJECTIVE_REGISTRY,
    register_objective,
    build_objective,
    AutoObjective,
    SupervisedObjective,
    RegularizedSupervisedObjective,
    TeacherForcingObjective,
    BehavioralObjective,
    VariationalObjective,
    LatentCircuitObjective,
    ConstrainedSupervisedObjective,
)
from .losses import (
    masked_mse,
    masked_cross_entropy,
    masked_nll,
    loss_mse,
    activity_l2,
    weight_l2,
    weight_l1,
    orthogonality_penalty,
    model_orthogonality_penalty,
    accuracy_classification,
    accuracy_general,
)
from .cv import (
    config_combination,
    behavior_cv_training,
    find_best_models_for_exp,
    CVResult,
)

__all__ = [
    "Trainer",
    "TrainingArguments",
    "Objective",
    "OBJECTIVE_REGISTRY",
    "register_objective",
    "build_objective",
    "AutoObjective",
    "SupervisedObjective",
    "RegularizedSupervisedObjective",
    "TeacherForcingObjective",
    "BehavioralObjective",
    "VariationalObjective",
    "LatentCircuitObjective",
    "ConstrainedSupervisedObjective",
    "masked_mse",
    "masked_cross_entropy",
    "masked_nll",
    "loss_mse",
    "activity_l2",
    "weight_l2",
    "weight_l1",
    "orthogonality_penalty",
    "model_orthogonality_penalty",
    "accuracy_classification",
    "accuracy_general",
    "config_combination",
    "behavior_cv_training",
    "find_best_models_for_exp",
    "CVResult",
]
